version: '3'
services:
  webservice:
    # container_name: api
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_PATH=/app
    volumes:
      - .:/app
    depends_on:
      - 'database'
  database:
    # container_name: 'mysql'
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=application
      - MYSQL_PASSWORD=applicationapi
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=multicalendar